# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  liquidsoap:
    container_name: liquidsoap
    image: m0rf30/docker-liquidsoap:latest
    tty: true
    command: 'liquidsoap -v /radio/radio.liq'
    volumes:
    - .:/radio
    - ./gmusic:/radio/gmusic
    - ./jingles:/radio/jingles
    network_mode: host

