# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  liquidsoap:
    container_name: gmusicproxy
    image: m0rf30/docker-gmusicproxy:latest
    tty: true
    volumes:
    - /etc/gmusicproxy.cfg:/etc/gmusicproxy.cfg

